# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Infrastructure/Http/' # Excluir la antigua ubicación
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Application\UseCase\User\RegisterUseCase:
        autowire: true
        public: true
        arguments:
            - '@App\Domain\Repository\UserRepositoryInterface'
    

    # Registra automáticamente todo en Infrastructure
    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude: '../src/Infrastructure/{Entity}'

    # Activar autowiring explícito para controladores
    App\Infrastructure\Http\Controllers\:
        resource: '../src/Infrastructure/Http/Controllers'
        tags: ['controller.service_arguments']  # ¡Esta línea es mágica!

    # Registra automáticamente UseCases
    App\Application\:
        resource: '../src/Application/*'
        exclude: '../src/Application/{DTO}'    

     # ¡AÑADE ESTO para registrar tus Use Cases!
    App\Application\UseCase\:
        resource: '../src/Application/UseCase/'
        autowire: true
        public: true  # Importante para tests
    

    # Bind de interfaces de dominio a implementaciones
    #App\Domain\Repository\ExampleRepositoryInterface: '@App\Infrastructure\Persistence\ExampleRepositoryImpl'    
    #App\Application\UseCase\EjemploUseCaseInterface: '@App\Application\UseCase\EjemploUseCase'
    #App\Domain\Repository\ProductRepositoryInterface: '@App\Infrastructure\Persistence\DoctrineProductRepository'
    App\Domain\Repository\UserRepositoryInterface: '@App\Infrastructure\Persistence\UserRepository'
    
    