name: Symfony CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Make scripts executable
      run: chmod +x ./scripts/*.sh

    - name: Build and start containers
      run: docker-compose up -d --build

    - name: Debug filesystem permissions
      run: |
        docker-compose exec -T php-fpm sh -c "cd /var/www/project && mount | grep project"
        docker-compose exec -T php-fpm sh -c "cd /var/www/project && ls -la && df -h ."
        docker-compose exec -T php-fpm sh -c "cd /var/www/project && touch test.txt && echo 'Â¿Puede escribir?' && rm -f test.txt"

    - name: Install dependencies
      run: docker-compose exec -T php-cli sh -c "cd /var/www/project && composer install --no-interaction --no-progress"

    - name: Run tests via scripts
      run: |
        ./scripts/test-unit.sh
        ./scripts/test-integration.sh
        ./scripts/test-functional.sh

    - name: Stop containers
      if: always()
      run: docker-compose down